[package]
name = "guanaco"
version = "0.1.0"
edition = "2021"
authors = ["Chris Parker <mrcsparker@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
